### PR TITLE
Create CNAME

### PR DESCRIPTION
**Pull request by josef-pkt**
following instructions here https://help.github.com/articles/adding-a-cname-file-to-your-repository/

### CODE REVIEW

**Comment by josef-pkt** [comment]
merging, it's a try and I hope it doesn't mess up doc accessibility

**Comment by josef-pkt** [comment]
statsmodels.github.io currently it redirects to the statsmodels.org parking page. 
Is supposed to go live in 10 minutes, if I didn't mess up

**Comment by TomAugspurger** [comment]
DNS caching can cause it to take longer to show up across the globe (not showing up here yet).

**Comment by josef-pkt** [comment]
my DNS sevice still shows Time To Live: 10 minutes, already for quite some time
so I wait unitl that is settled before I switch the CNAME back on on github

(It's night time here in France and I cannot wait.)

BTW: the sourceforge documentation is back online

**Comment by TomAugspurger** [comment]
Just saw that. Enjoy France!

**Pull request merged**
