### PR TITLE
DOC: update versions

### PR DESCRIPTION
**Pull request by thequackdaddy**
This is a little helper script to generate the versions. It could be run by doctr on commit... 

Handling the "v" prefixes as well as changing to loose version to handle "rcX" suffixes.

cc @bashtage

### CODE REVIEW

**Comment by thequackdaddy** [comment]
@josef-pkt Any chance either @bashtage or I could have commit privileges on this repo to? Need to make a few small changes to the docs.

**Comment by TomAugspurger** [comment]
LGTM.

I can't give permission, but I can merge @thequackdaddy. Good to go?

**Comment by josef-pkt** [comment]
@thequackdaddy I added you and Kevin to the members

**Comment by thequackdaddy** [comment]
Thanks, all.

**Pull request merged**
