### PR TITLE
update dev

### PR DESCRIPTION
**Pull request by TomAugspurger**
As of yesterday.

### CODE REVIEW

**Comment by josef-pkt** [comment]
Thanks a lot

Finally some shiny new docs again.
Do you want to mention/announce it on the mailing list or should I?

**Comment by TomAugspurger** [comment]
I put it in that thread asking about Statespace models, but if you think it warrants a more public announcement then by all means go for it.

Ideally I'll get this hooked into the CI system so that they're built regularly.

**Comment by josef-pkt** [comment]
@TomAugspurger   Question: how did you get around numpydoc problem which didn't work for me on python 3?
I needed to upgrade to the latest numpydoc, replacing the one we have included, to be able to build the documentation on python 3.4

**Comment by TomAugspurger** [comment]
I upgraded to the latest numpy doc (from pip) and deleted numpydoc from the `sphinxext/numpy` directory. Is there a reason to bundle it anymore? I've got a writeup of all the changes I've made that I'll post in the other thread when I get a chanced.

**Comment by josef-pkt** [comment]
I don't think we need to bundle it anymore.

my experience with the doc build last week is noted here
https://github.com/statsmodels/statsmodels/issues/2312

**Pull request merged**
